exclude: [LICENSE, Resources, Gemfile, Gemfile.lock]
baseurl: /Parsnip
sass:

    # loading path from site root
    # default to _sass
    sass_dir: _includes/css

    # style : nested (default), compact, compressed, expanded
    #         :nested, :compact, :compressed, :expanded also works
    style: :compressed
